### ISSUE TITLE
Tracking issue: skip attributes

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1978]
[RFC 2103](https://github.com/rust-lang/rfcs/pull/2103) will let us use `#[rustfmt::skip]` without a warning.

- [ ] merge RFC 2103 (nrc)
- [ ] implement the new scoped attributes in Rust
- [ ] recognise the scoped attributes in rustfmt
- [ ] document and recommend the new attributes
- [ ] stabilise the new attributes in Rust
- [ ] deprecate the old attributes

**Comment by nrc** [comment]
There is an implementation at https://github.com/rust-lang/rust/pull/47773 but it needs a test fixing and a rebase.

**Comment by topecongiro** [comment]
https://github.com/rust-lang/rust/issues/51277 is closed 🙌
