### ISSUE TITLE
Meta: make tidy parity

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#20]
The first big goal for rustfmt should be parity with `make tidy`, i.e., we do all the checks that `make tidy` does and is usable as part of the rust distro build process. This needs three things - feature parity, non-bugginess and configurability.
## Feature parity

Need to find out exactly what `make tidy` does, but things that come to mind are: warnings on cfg(stage0), checking for TODO, checking licenses.
## Non-bugginess

In order to be part of the build process, we need to be able to run rustfmt on the whole repo without breaking anything. This will need lots of testing and some big PRs to the Rust repo for the initial reformatting.

To make this tractable, we'll want to turn rustfmt on one crate at a time and keep the make tidy step until the end (it might make sense to keep make tidy forever for the test suite, although it would be nice to kill it.
## Configurability

There will be bugs, we need to be able to turn rustfmt off for some sections of a file until rustfmt can be fixed. We'll also want to evolve rustfmt (make tidy parity does not (and should not) require all formatting rules are enforced, and we'll want to add more rules as time goes by), we'll want to be able to feature gate some features of rustfmt so that they can be tested without applying to the rust repo or forking rustfmt.

We'll also need configurability for some of the `make tidy` features, for example license checking, since different projects will have different licences.

**Comment by nrc** [comment]
Performance might also be an issue. In the case where we don't modify anything, we should be pretty fast - i.e., ballpark with `make tidy`. That will probably mean we need to at the least not write out if nothing has changed (assuming writing to a file is slower than comparing two long strings, which might not be the case if writing is in part async, but I don't think it is).

Alternatively, we could skip checking files which have not changed at all since the last check. But that would require keeping metadata around, and could break easily because multi-user time is hard.

We might just need to optimise a lot too.

**Comment by nrc** [comment]
TODO list

- [x] check for trailing whitespace
- [x] check for overlong lines
- [ ] #209 check for license
- [ ] set an exit code for warnings
- [x] warn on TODOs
- [ ] match target for formatting all crates (issue for Rust, rather than rustfmt, requires rustfmt in tree some how, probably a submodule, and probably lots of details to sort out)
- [ ] other features? I know there are some more I some times see
